Model:
    name: CLAMMB
    size_arg: small
    n_classes: 4
    input_dim: 1024
    dropout: True

Optimizer:
    opt: adam
    lr: 0.0005
    opt_eps: null # eps in parameter
    opt_betas: !!python/tuple [0.9, 0.999] # beta in parameter
    momentum: null # momentum in parameter
    weight_decay: 10.e-5 # weight decay in parameter

Data:
    feature_kind: CTrans # UNI or CTrans or res50
    model_path: LEOPARD/results/CLAMMB/0/epoch_19_index_0.6620111731843575.pth
    data_dir: /data115_2/LEOPARD/FEATURES/Leopard_512_at_0.25mpp/
    save_dir: /data115_2/jsh/LEOPARD/results/

Lr_scheduler:
    _if: True

# General:
#     comment: 
#     seed: &seed 2021
#     gpus: [1,2]
#     epochs: &epoch 1000 
#     patience: -1 # early stopping patience (used to build callback)
#     monitor: 'val_balanced_accuracy' # early stopping monitor
#     mode: 'max' # 'max' or 'min', early stopping mode
#     server: train # train or test
#     log_path: logs # the root dir to save logs

# Data:
#     dataset_name: ubc_data
#     data_shuffle: False
#     data_dir:  /data112/fzj/UBC-OCEAN/MILMethods/data/ctranspath_20x_256_aug/pt_files/
#     # data_dir: /data112/fzj/UBC-OCEAN/MILMethods/data/features/pt_files
#     split_dir: data/split_1129
#     label_dict: {'HGSC': 0, 'EC': 1, 'CC': 2, 'LGSC': 3, 'MC': 4}

#     train_dataloader:
#         batch_size: 1 
#         num_workers: 4

#     test_dataloader:
#         batch_size: 1
#         num_workers: 4


# Loss:
#     base_loss: CrossEntropyLoss
