Model:
    name: Patch_GCN
    size_arg: small
    n_classes: 4
    input_dim: 1024 
    edge_agg: spatial # latent or spatial
    model_graph: True

Optimizer:
    opt: adam
    lr: 0.0005
    opt_eps: null # eps in parameter
    opt_betas: !!python/tuple [0.9, 0.999] # beta in parameter
    momentum: null # momentum in parameter
    weight_decay: 10.e-5 # weight decay in parameter

Data:
    feature_kind: res50 # UNI or CTrans or res50
    data_dir: /data115_2/jsh/LEOPARD_GCN/Leopard_512_at_0.25mpp/component_features
    save_dir: /data115_2/jsh/LEOPARD/results/
    use_h5: False

Lr_scheduler:
    _if: True
    