Model:
    name: Patch_GCN
    size_arg: small
    n_classes: 4
    input_dim: 768 
    edge_agg: spatial # latent or spatial
    model_graph: True

Optimizer:
    opt: adam
    lr: 0.0005
    opt_eps: null # eps in parameter
    opt_betas: !!python/tuple [0.9, 0.999] # beta in parameter
    momentum: null # momentum in parameter
    weight_decay: 10.e-5 # weight decay in parameter

Data:
    feature_kind: CTrans # UNI or CTrans or res50
    data_dir: /data115_2/jsh/LEOPARD_GCN/Leopard_512_at_0.25mpp
    save_dir: /data115_2/jsh/LEOPARD/results_temp/
    use_h5: False
    # model_path: /data115_2/jsh/LEOPARD/results_discrect/Patch_GCN/mpdel_graph/CTrans_3000/0/epoch_3_index_0.6948480845442536.pth  # 预测错误
    # model_path: /data115_2/jsh/LEOPARD/results_discrect/Patch_GCN/mpdel_graph/CTrans/2/epoch_2_index_0.6731413261888815.pth
    # model_path: LEOPARD/results_discrect/Patch_GCN/mpdel_graph/CTrans_3000/3/epoch_2_index_0.6761633428300095.pth   # 过滤1000
    model_path: /data115_2/jsh/LEOPARD/results_discrect/Patch_GCN/mpdel_graph/CTrans/0/epoch_1_index_0.6908850726552179.pth

    csv_path: /data115_2/jsh/LEOPARD/leopard_labels/training_labels.csv
    split_dir: /data115_2/jsh/LEOPARD/splits_test

Lr_scheduler:
    _if: True
    