Model:
    name: TransMIL
    n_classes: 4
    input_dim: 1536
    model_graph: False

Optimizer:
    opt: adam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Data:
    feature_kind: CTrans # UNI or CTrans or res50
    # model_path: LEOPARD/results/TransMIL/res50_pre/0/epoch_15_index_0.7373134328358208.pth
    model_path: /data115_2/jsh/LEOPARD/results/TransMIL/CTrans/3/epoch_6_index_0.7628541448058762.pth
    data_dir: /data115_2/LEOPARD/FEATURES/Leopard_512_at_0.25mpp/
    save_dir: /data115_2/jsh/LEOPARD/results/

Lr_scheduler:
    _if: True

