Model:
    name: TransMIL
    n_classes: 4
    input_dim: 768
    model_graph: False

Optimizer:
    opt: adam
    lr: 0.0002
    opt_eps: null 
    opt_betas: null
    momentum: null 
    weight_decay: 0.00001

Data:
    feature_kind: CTrans # UNI or CTrans or res50
    data_dir: /data115_2/LEOPARD/FEATURES/Leopard_512_at_0.25mpp/
    data_dir_multi_scale: /data115_2/jsh/LEOPARD_features_2048_at_0.25mpp/
    save_dir: /data115_2/jsh/LEOPARD/results_multi_scale/three/
    multi_scale: True
    use_h5: False
    model_path: 
    csv_path: /data115_2/jsh/LEOPARD/leopard_labels/training_labels.csv
    split_dir: /data115_2/jsh/LEOPARD/splits_5fold/

Lr_scheduler:
    _if: True

# '/data115_2/jsh/LEOPARD_features_2048_at_0.25mpp/CTrans/pt_files/case_radboud_0169.pt'
# '/data115_2/jsh/LEOPARD_features_2048_at_0.25mpp/CTranspath/pt_files/case_radboud_0169.pt'